# Generated by Django 2.2.6 on 2019-10-27 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20191027_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='creator',
        ),
    ]
