# Generated by Django 2.2.6 on 2019-10-27 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_todolist_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
